AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Console InStock Alert App
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Parameters:
  DiscordStatusNotificationURL:
    Type: String
    Description: "The discord webhoook status notification URL"
  DiscordNotificationURL:
    Type: String
    Description: "The discord webhoook notification URL"

Resources:
  StockScanner:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: "StockScanner"
      CodeUri: stock-scanner/.build/
      Handler: index.handler
      Runtime: nodejs14.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BuyBotStateTable
      Environment:
        Variables:
          DISCORD_BOT_STATUS_CHECK_URL: !Ref DiscordStatusNotificationURL
          DISCORD_NOTIFICATION_URL: !Ref DiscordNotificationURL
          TABLE_NAME: "buy-bot-state-table"

  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: "rate(1 minute)"
      State: "ENABLED"
      Targets: 
        - 
          Arn: !GetAtt StockScanner.Arn
          Id: "TargetStockScanner"

  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref "StockScanner"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "ScheduledRule"
          - "Arn"

  BuyBotStateTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey: 
        Name: "console"
        Type: String
      TableName: buy-bot-state-table
      